const juicy = [
      "Wat is het vreemdste dat je ooit in het openbaar hebt gedaan?",
      "Wat is iets beschamends dat je hebt gedaan en nooit aan iemand hebt verteld?",
      "Wat is het meest bizarre bericht dat je ooit hebt ontvangen?",
      "Wat is het meest cringy dat je ooit op sociale media hebt gezet?",
      "Hoeveel verandert jouw persoonlijkheid als je bij verschillende mensen bent?",
      "Wat is het aardigste dat iemand ooit voor jou heeft gedaan?",
      "Als iemand een boek over jou zou schrijven, hoe zou het heten?",
      "Geloof je in het hebben van één beste vriend?",
      "Hoe definieer jij schoonheid?",
      "Wat vind je de meest irritante eigenschap die iemand kan hebben?",
      "Wie vind jij dat geen beroemdheid zou moeten zijn?",
      "Wie was je meest onverwachte crush?",
      "Wanneer en waar was je eerste kus?",
      "Met wat voor type persoon zie jij jezelf uiteindelijk eindigen?",
      "Wat is jouw guilty pleasure-film of tv-show?",
      "Wat is jouw 'Romeinse Rijk'? (Iets waar je constant aan denkt).",
      "Wat is het beste roddeltje dat je ooit hebt gehoord?",
      "Welk deel van jouw sterrenbeeld herken je het meest in jezelf?",
      "Wat is jouw favoriete reisverhaal?",
      "Wat is het spannendste dat je ooit hebt gedaan?",
      "Wat is het meest illegale dat je ooit hebt gedaan?",
      "Heb je ooit iets gestolen? Wat was het?",
      "Heb je ooit een leugen verteld die gigantisch uit de hand liep?",
      "Wat is de ergste nachtmerrie die je ooit hebt gehad?",
      "Wat zou je doen als je 24 uur onzichtbaar zou zijn?",
      "Wat is het meest gênante moment dat je ooit in een romantische situatie hebt gehad?",
      "Heb je ooit een crush gehad op iemand die je absoluut niet zou moeten hebben?",
      "Wat is de meest gewaagde beslissing die je ooit hebt genomen?",
      "Heb je ooit een flirt volledig verkeerd geïnterpreteerd?",
      "Heb je ooit een date moeten faken om te ontsnappen?",
      "Heb je ooit een vriend verraden? Wat gebeurde er?",
      "Wat is het domste dat je hebt gedaan toen je dronken was?",
      "Heb je ooit een geheime relatie gehad?",
      "Wat is het raarste wat iemand ooit tegen je gezegd heeft?",
      "Heb je ooit een one-night stand gehad?",
      "Wat is de meest rare plek waar je ooit in slaap bent gevallen?",
      "Wat is het raarste dat je ooit online hebt gekocht?",
      "Wat is je grootste guilty pleasure qua eten?",
      "Wat is het meest gênante dat ooit op je telefoon stond?",
      "Heb je ooit een bericht gestuurd naar de verkeerde persoon? Wat gebeurde er?",
      "Wat is het raarste gerucht dat je ooit over jezelf hebt gehoord?",
      "Heb je ooit iemands telefoon doorgespit zonder dat diegene het wist?",
      "Wat is de gekste droom die je ooit hebt gehad?",
      "Wat is de stoutste leugen die je ooit hebt verteld?",
      "Wat is het meest risicovolle dat je ooit hebt gedaan?",
      "Heb je ooit een crush gehad op een leraar?",
      "Wat is het meest gênante dat je ouders ooit over je hebben ontdekt?",
      "Heb je ooit gedaan alsof je iemand niet kende terwijl je dat wel deed?",
      "Wat is het raarste excuus dat je ooit hebt verzonnen?",
      "Heb je ooit iemands geheim doorverteld?",
      "Wat is het meest cringy openingszin die ooit tegen je is gebruikt?",
      "Wat is het raarste wat je ooit hebt opgezocht op internet?",
      "Wat is de domste reden waarom je ooit ruzie hebt gehad?",
      "Heb je ooit gedaan alsof je ziek was om onder iets uit te komen?",
      "Wat is het meest onverwachte dat je ooit in iemand aantrok?",
      "Heb je ooit iemand geghost? Waarom?",
      "Wat is je grootste onzekerheid?",
      "Heb je ooit een weddenschap verloren en moest je iets gênants doen?",
      "Wat is het grappigste wat je ooit in een openbaar toilet hebt gehoord?",
      "Wat is de gekste manier waarop je ooit iemands aandacht hebt proberen te trekken?",
      "Heb je ooit een privégesprek per ongeluk met iemand gedeeld?",
      "Wat is het domste dat je ooit in een dronken bui hebt beloofd?",
      "Heb je ooit gedaan alsof je een bericht niet hebt gezien terwijl je dat wel had?",
      "Wat is het meest ongemakkelijke moment dat je met je ex hebt gehad?",
      "Wat is de meest gênante bijnaam die je ooit hebt gehad?",
      "Wat is de domste fout die je ooit in een relatie hebt gemaakt?",
      "Heb je ooit in de problemen gezeten door iets wat je op social media hebt geplaatst?",
      "Wat is de vreemdste versiertruc die ooit op jou is uitgeprobeerd?",
      "Wat is het meest gênante misverstand dat je ooit hebt gehad?",
      "Heb je ooit een romantisch gebaar gehad dat totaal verkeerd uitpakte?",
      "Heb je ooit gefaket dat je een talent had om indruk te maken op iemand?",
      "Wat is het meest ongemakkelijke familiegeheim dat je ooit hebt gehoord?",
      "Heb je ooit per ongeluk 'Ik hou van je' gezegd tegen de verkeerde persoon?",
      "Wat is het raarste dat je ooit in een hotelkamer hebt gevonden?",
      "Heb je ooit iemand laten geloven dat je iemand anders was?",
      "Heb je ooit iets gedaan om indruk te maken op iemand en werd het een ramp?",
      "Wat is de vreemdste plek waar je ooit bent wakker geworden?",
      "Heb je ooit een onverwachte gast betrapt in je huis?",
      "Wat is het raarste dat je ooit hebt moeten googelen?",
      "Heb je ooit een prank uitgehaald die totaal verkeerd ging?",
      "Wat is het ongemakkelijkste moment dat je met je schoonouders hebt gehad?",
      "Wat is het raarste wat je ooit in een restaurant hebt besteld?",
      "Heb je ooit een droom gehad die zo echt voelde dat je dacht dat het echt was?",
      "Wat is het gekste verhaal dat je ooit hebt gehoord dat daadwerkelijk waar bleek te zijn?",
      "Wat is het meest ongepaste moment waarop je hardop moest lachen?",
      "Heb je ooit een enorm domme fout gemaakt tijdens je werk of school?",
      "Wat is het gênantste wat je ooit tegen een crush hebt gezegd?",
      "Wat is het raarste dat iemand ooit in je DM’s heeft gestuurd?",
      "Heb je ooit iemand betrapt op iets waar ze zich enorm voor schaamden?",
      "Wat is het raarste cadeautje dat je ooit hebt gekregen?",
      "Wat is het meest beschamende wat je ooit tegen je baas of docent hebt gezegd?",
      "Heb je ooit je ouders betrapt op iets dat je liever niet had willen zien?",
      "Heb je ooit zo hard gelachen dat je iets uit je neus of mond spuwde?",
      "Wat is de domste beslissing die je ooit hebt genomen omdat je onder groepsdruk stond?",
      "Wat is het grootste geheim dat je ooit hebt bewaard?",
      "Heb je ooit iemand gelogen over hoe je je voelde om hun gevoelens te sparen?"
    ];  

const random = [
    "Heb je ooit een crush gehad op een tekenfilmfiguur?",
    "Zou je ooit een eigen bedrijf starten?",
    "Wat vind jij de slechtste feestdag?",
    "Wat stel je op dit moment uit?",
    "Bouwde je vroeger forten als kind? Hoe zagen ze eruit?",
    "Wat vind je de beste grap of prank aller tijden?",
    "Als je een nieuw muziekinstrument mocht ontwerpen, wat zou je maken en hoe zou het klinken?",
    "Is er iets waar je een week voor in de rij zou wachten om te doen, te zien of te krijgen?",
    "Als bloemen konden praten, hoe zouden ze klinken?",
    "Als je maar één saus of dressing voor de rest van je leven mocht eten, welke zou je kiezen?",
    "Als je een huishoudelijk voorwerp zou zijn, wat zou je kiezen?",
    "Als je een geest was, hoe zou je mensen dan lastigvallen?",
    "Welke lichaamsfunctie zou je willen laten verdwijnen?",
    "Als je een heel vat van één ding moest opeten, wat zou je kiezen?",
    "Als je iets uit een kanon mocht schieten, wat zou het zijn?",
    "Heb je een favoriete familietraditie?",
    "Beschrijf je droomhuis.",
    "Wat is jouw favoriete flauwe mop?",
    "Als je je brein een naam moest geven, hoe zou je het noemen?",
    "Welke studie zou je in een spoedcursus willen volgen?",
    "Wat is jouw favoriete vorm van transport?",
    "Als je voor de rest van je leven maar één kleur mocht dragen, welke zou je kiezen?",
    "Hoe goedgelovig vind je jezelf?",
    "Wat denk je dat je precies over 10 jaar aan het doen bent?",
    "Wat is het pittigste eten dat je ooit hebt gegeten?"
  ];

const bestfriend = [
    "Wat maakt jou het meest beschaamd?",
    "Wat is jouw liefdestaal?",
    "Hoe word je het liefst getroost als je verdrietig of van streek bent?",
    "Wat is je allerbeste herinnering?",
    "Waar hoop je over vijf jaar te zijn? Over tien? Over vijftien?",
    "Wanneer heb je je het meest uitgedaagd gevoeld?",
    "Ben je ooit gepest?",
    "Welke beroemdheid zou je als je andere beste vriend willen en waarom?",
    "Met welk familielid ben je het meest close?",
    "Wat doe je als niemand anders in de buurt is?",
    "Wat is één ding dat de meeste mensen niet over jou weten?",
    "Wat denk jij dat er gebeurt als we sterven?",
    "Wil je ooit kinderen? Hoeveel?",
    "Wat is de ergste verwonding die je ooit hebt gehad?",
    "Wat is je vroegste jeugdherinnering?",
    "Wat houdt je 's nachts wakker als je niet kan slapen?",
    "Wat is de laatste leugen die je hebt verteld?",
    "Wat is het mooiste compliment dat je ooit hebt gekregen?",
    "Wat beschouw jij als het ultieme comfortfood?",
    "Wat vind je je mooiste fysieke eigenschap?",
    "Wat zijn de drie dingen die jou het meeste stress bezorgen?",
    "Wat zijn de drie manieren waarop jij met stress omgaat?",
    "Als je maar drie dingen op je bucketlist mocht hebben, welke zouden dat zijn?",
    "Als je ooit zou trouwen, hoe ziet jouw droomaanzoek eruit?",
    "Wanneer heb je je het meest geliefd gevoeld?",
    "Als je een pretpark mocht ontwerpen, hoe zou het eruitzien?",
    "Wanneer was de laatste keer dat je je geïnspireerd voelde om iets te creëren?",
    "Heb je ooit een 'vriendschapsbreuk' meegemaakt? Wat heb je daarvan geleerd?",
    "Wie was je eerste vriend en is die nog steeds in je leven?",
    "Zou je ooit een langeafstandsrelatie overwegen?",
    "Wat vind jij de beste manier om conflicten op te lossen?",
    "Hoe hebben jouw ouders elkaar ontmoet?",
    "Vind je dat je een gezonde relatie hebt met sociale media?",
    "Wie was je favoriete leraar of lerares?",
    "Wat zijn je favoriete kindernamen?",
    "Is er een moment waarop ik je extra gesteund heb gevoeld?",
    "Hoe kan ik een betere vriend voor je zijn?",
    "Wat betekent vriendschap voor jou?"
  ];

const deep = [
    "Waar voel je je het meest schuldig over?",
    "Met wie zou je graag opnieuw contact willen?",
    "Wat bezorgt jou de meeste stress?",
    "Wanneer voel je je het meest alleen?",
    "Ben je ooit verliefd geweest?",
    "Geloof je in liefde op het eerste gezicht?",
    "Wat is de grootste les die je uit je laatste relatie hebt geleerd?",
    "Wat is één ding dat je aan jezelf zou willen veranderen?",
    "Aan wie zou je graag je excuses willen aanbieden?",
    "Wat was het laatste keerpunt in je leven?",
    "Wat helpt jou om door moeilijke dagen heen te komen?",
    "Bij wie voel je je het meest veilig?",
    "Wat is je favoriete jeugdherinnering?",
    "Wat is de grootste sprong in het diepe die je ooit hebt genomen?",
    "Naar wie kijk je het meest op en welke eigenschappen bewonder je in die persoon?",
    "Wat is je grootste angst?",
    "Wie was de laatste persoon die je aan het huilen bracht en waarom?",
    "Wanneer voelde je je het meest trots?",
    "Heb je ergens spijt van? Zo ja, waarvan?",
    "Wat is het mooiste cadeau dat je ooit hebt gekregen? Van wie was het en waarom was het zo speciaal?",
    "Als je één ding aan jezelf kon veranderen, wat zou het zijn?",
    "Geloof je in soulmates?",
    "Wat is het moeilijkste afscheid dat je ooit hebt moeten nemen?",
    "Wanneer was de laatste keer dat je jaloers was en waarom?",
    "Wat is de slechtste beslissing die je ooit hebt genomen?",
    "Hoe denk je dat je zal zijn op je oude dag?",
    "Wat is iets wat je als onvergeeflijk beschouwt?",
    "Geloof je in monogamie?"
  ];

const fun = [
    "Zou je liever een expert zijn in één ding, of best goed in veel dingen?",
    "Wat is je favoriete bezit en waarom?",
    "Heb je ooit je toekomst laten voorspellen?",
    "Bestel je liever eten of eet je liever buiten de deur?",
    "Wat is de eerste film die je je herinnert in de bioscoop te hebben gezien?",
    "Wat is je favoriete podcast?",
    "Wat was je meest twijfelachtige kapsel of modieuze keuze?",
    "Als geld geen rol speelde, wat zou je kopen?",
    "Waar droomde je afgelopen nacht over?",
    "Wanneer heb je in je leven het hardst gelachen?",
    "Wat doe je als niemand anders in de buurt is?",
    "Waar wil je het liefst naartoe reizen?",
    "Als je de rest van je leven maar één ding mocht eten, wat zou het zijn?",
    "Welk boek heeft de grootste impact op je gehad?",
    "Wat is je favoriete reclame?",
    "Welke eigenschappen trekken jou het meest aan in een liefdespartner?",
    "Je wint net €10.000—wat ga je ermee doen?",
    "Wat is het gelukkigste dat je ooit is overkomen?",
    "Wat is je favoriete manier om te sporten?",
    "Hou je van achtbanen?",
    "Wat is de klus in huis die je het meest haat, en waarom?",
    "Wat is je favoriete feestdag en waarom?",
    "Wat is de slechtste date die je ooit hebt gehad?",
    "Als je een tatoeage zou nemen, wat zou je kiezen en waarom?",
    "Als je drie wensen had, wat zou je wensen?",
    "Als je moest kiezen, zou je dan een hond of een kat nemen?",
    "Geloof je in buitenaards leven?",
    "Als je president zou zijn, wat is het eerste dat je zou veranderen in dit land?",
    "Als je in een ander tijdperk moest leven, welk tijdperk zou je kiezen?",
    "Wie was je allereerste crush?",
    "Welke vreemde taal zou je graag vloeiend willen spreken en waarom?",
    "Wat is je absolute favoriete dessert?",
    "Geloof je in geesten?",
    "Wat is je overlevingsplan tijdens een zombie-apocalyps?",
    "Als je een dier was, welk dier zou je zijn?",
    "Als je een alter ego moest creëren, wie zou dat zijn en hoe zou je hem of haar noemen?",
    "Wat is jouw nummer 1 karaoke-liedje?",
    "Ben je ooit op een blind date geweest?",
    "Wat was je eerste MSN-naam of e-mailadres?",
    "Wat is je favoriete willekeurige feitje?",
    "Wat was je eerste concert?",
    "Welke modeperiode had volgens jou de beste trends?",
    "Als er een liedje speelde elke keer dat je een kamer binnenkwam, welk liedje zou dat zijn?",
    "Wat is je huidverzorgingsroutine?",
    "Ben je ooit naar zomerkamp geweest?",
    "Wanneer was de laatste keer dat je echt de natuur hebt ervaren?",
    "Voel je je jong van geest, of juist een oude ziel?",
    "Wat betekent je naam en waarom hebben je ouders die gekozen?",
    "Welke onverwachte film maakt je altijd aan het huilen?"
  ];

const newfriend = [
    "Wat zijn je voornaamwoorden?",
    "Hoe zou jouw perfecte dag eruitzien? Plan hem van 's ochtends tot bedtijd.",
    "Wat is je sterrenbeeld?",
    "Wat is je Enneagram-type?",
    "Ben je op vakantie meer het type dat bij het zwembad relaxt of een avonturier die eropuit trekt?",
    "Beschouw je jezelf als religieus of spiritueel?",
    "Welke studierichting overweeg je en waarom?",
    "Als je maar naar één zanger of band mocht luisteren voor de rest van je leven, wie zou je kiezen?",
    "Wat is jouw go-to gerecht als je moet koken?",
    "Ben je bijgelovig?",
    "Wat is je favoriete bordspel?",
    "Wie is de beste filmvillain ooit?",
    "Wie is je favoriete persoon om te volgen op TikTok? En op Instagram?",
    "Had je als kind een denkbeeldige vriend?",
    "Als je jezelf in drie woorden moest omschrijven, welke zou je kiezen? Welke woorden zouden je vrienden voor jou kiezen?",
    "Heb je fobieën?",
    "Wat zijn jouw drie grootste ergernissen?",
    "Wat is je favoriete kleur en wat is je minst favoriete kleur?",
    "Hoe ziet jouw droomvakantie eruit?",
    "Ben je competitief?",
    "Wat is een moeilijke ervaring waar je van hebt geleerd en door bent gegroeid?",
    "Hoe is jouw relatie met je ouders?",
    "Volg je meestal je hart of je hoofd?",
    "Wat is het meest onverwachte of ongewone item op je bucketlist?",
    "Hoe was je laatste romantische relatie?",
    "Wat is een waarde waar je nooit op zou toegeven?",
    "Wat is je absolute droombaan?",
    "Als je een superkracht mocht kiezen, welke zou je nemen?",
    "Welke tv-show zet je op als je gewoon wilt ontspannen en je beter wilt voelen?",
    "Wat was de laatste film die je in de bioscoop hebt gezien?",
    "Als je kon tijdreizen, waar zou je naartoe gaan?",
    "Wat eet je meestal als ontbijt?",
    "Wat is je favoriete plant of bloem?",
    "Wat is je favoriete seizoen en waarom?",
    "Wie laat jou altijd lachen?",
    "Wat denk je dat jouw beste eigenschap is?",
    "Wat is jouw definitie van succes?",
    "Welke film heb je het vaakst gezien?",
    "Heb je verborgen talenten?",
    "Wat is de beste Halloween-outfit die je ooit hebt gedragen?",
    "Zou je liever aan de oceaan wonen of in de bergen?",
    "Wat is de langste reis die je ooit hebt gemaakt?",
    "Ben je meer een linkerhersenhelft- of rechterhersenhelft-persoon?",
    "Wat is je meest gebruikte emoji?",
    "Wat is een slechte gewoonte die je probeert af te leren?",
    "Wat is de engste film die je ooit hebt gezien?",
    "Ben je een ochtendmens of een nachtuil?",
    "Laad je het liefst op in je eentje of in gezelschap?",
    "Wat is het beste museum waar je ooit bent geweest?",
    "Wanneer kunnen we weer afspreken?"
  ];

export {
    juicy,
    random,
    bestfriend,
    deep,
    fun,
    newfriend
};